"""
Environment file generator.

Generates .env files from provisioned GCP resources.
"""

import secrets
import string
from pathlib import Path
from typing import Optional

from biz2bricks_infra.gcloud.commands import run_gcloud_command


def generate_password(length: int = 32) -> str:
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_env_file(
    output: str,
    project_id: str,
    region: str,
    db_password: str | None = None,
    jwt_secret: str | None = None,
    refresh_secret: str | None = None,
) -> bool:
    """
    Generate .env file from provisioned GCP resources.

    Args:
        output: Output file path
        project_id: GCP project ID
        region: GCP region
        db_password: Database password (auto-generated if None)
        jwt_secret: JWT secret key (auto-generated if None)
        refresh_secret: Refresh token secret key (auto-generated if None)

    Returns:
        True if successful, False otherwise
    """
    print(f"Generating {output} from GCP resources...")

    # Discover Cloud SQL instance
    cloud_sql_instance = _discover_cloud_sql(project_id, region)

    # Discover GCS bucket
    bucket_name = _discover_gcs_bucket(project_id)

    # Use provided secrets or generate new ones
    password_was_generated = not db_password
    jwt_secret = jwt_secret or generate_password(64)
    refresh_secret = refresh_secret or generate_password(64)
    db_password = db_password or generate_password(32)

    # Build .env content
    content = f"""# Generated by biz2bricks generate-env
# Project: {project_id}
# Region: {region}

# ============ GCP Configuration ============
GCP_PROJECT_ID="{project_id}"
CLOUD_SQL_INSTANCE="{cloud_sql_instance}"
USE_CLOUD_SQL_CONNECTOR=true
CLOUD_SQL_IP_TYPE="PUBLIC"

# ============ Database ============
DATABASE_NAME="doc_intelligence"
DATABASE_USER="postgres"
DATABASE_PASSWORD="{db_password}"

# ============ Storage ============
GCS_BUCKET_NAME="{bucket_name}"

# ============ Authentication ============
JWT_SECRET_KEY="{jwt_secret}"
REFRESH_SECRET_KEY="{refresh_secret}"
ACCESS_TOKEN_EXPIRE_MINUTES=120
REFRESH_TOKEN_EXPIRE_DAYS=7

# ============ Application ============
ENVIRONMENT="production"
DEBUG=false
LOG_LEVEL="INFO"

# ============ Cache ============
CACHE_ENABLED=true
CACHE_BACKEND="memory"
CACHE_DEFAULT_TTL=300
"""

    # Write file
    output_path = Path(output)
    output_path.write_text(content)
    print(f"Generated {output}")

    # Print summary
    print("\n=== Summary ===")
    print(f"  Cloud SQL: {cloud_sql_instance or 'Not found'}")
    print(f"  GCS Bucket: {bucket_name or 'Not found'}")
    print(f"  Output: {output}")

    if not cloud_sql_instance:
        print("\n⚠️  Cloud SQL instance not found. Update CLOUD_SQL_INSTANCE manually.")
    if not bucket_name:
        print("\n⚠️  GCS bucket not found. Update GCS_BUCKET_NAME manually.")

    if password_was_generated:
        print("\n⚠️  DATABASE_PASSWORD was auto-generated. Update Cloud SQL user password to match.")

    return True


def _discover_cloud_sql(project_id: str, region: str) -> Optional[str]:
    """Discover Cloud SQL instance in project."""
    success, output = run_gcloud_command([
        "sql", "instances", "list",
        "--project", project_id,
        "--format=value(name,region)",
    ])

    if not success or not output:
        return None

    # Parse output and find matching instance
    for line in output.strip().split("\n"):
        parts = line.split()
        if len(parts) >= 2:
            instance_name = parts[0]
            instance_region = parts[1]
            if instance_region == region:
                return f"{project_id}:{region}:{instance_name}"

    # Return first instance if no region match
    if output:
        parts = output.strip().split("\n")[0].split()
        if len(parts) >= 2:
            return f"{project_id}:{parts[1]}:{parts[0]}"

    return None


def _discover_gcs_bucket(project_id: str) -> Optional[str]:
    """Discover GCS bucket in project."""
    from biz2bricks_infra.gcloud.commands import run_gsutil_command

    success, output = run_gsutil_command(["ls", "-p", project_id])

    if not success or not output:
        return None

    # Parse output and find first bucket
    for line in output.strip().split("\n"):
        if line.startswith("gs://"):
            # Extract bucket name
            bucket = line.replace("gs://", "").rstrip("/")
            # Skip system buckets
            if not bucket.startswith("artifacts.") and not bucket.startswith("gcf-"):
                return bucket

    return None
